### ISSUE TITLE
[Feat] 구현 WeatherKit으로부터 실시간 날씨 받아오기

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#14]
# ✏️ Description
- WeatherKit으로부터 실시간 날씨 받아오기

# 🛠️ Todo
- [ ] AttendanceView에서 버튼 클릭 후 WeatherKit으로부터 실시간 날씨 받아오기
- [ ] AttendanceCompletedView에서 시작하기 버튼 클릭 후 AttendanceRecordSheet에 날씨 정보 저장하기
- [ ] AptView에서 주기적으로 실시간 날씨 받아오기
