### ISSUE TITLE
[Feat] 구현 SceneWeather에서 Image를 Lottie 파일로 대체하기

### ISSUE THREAD

**Issue by yejinms** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#21]
# ✏️ Description
- AptView 내 날씨 레이어인 SceneWeather에서 현재 날씨 case 별로 들어가있는 Image 에셋을 Lottie 파일로 대체

# 🛠️ Todo
- [ ] Color+Extension 의 weather 구조체 안의 날씨별 이미지 파일을 Lottie 파일명으로 바꾸기
- [ ] SceneWeather에서 case 별로 Lottie 파일 불러와서 화면 사이즈 맞게 배치하기
- [x] lottie-ios Package 다운받기
- [ ] LottieView 주석처리 된 거 되돌리고 루프 애니메이션 잘 돌아가나 확인하기
- [ ] 미세한 루프 타이밍 조정해서 마무리하기
- [ ] Lottie JSON 파일 에셋 추가
