### ISSUE TITLE
[Feat] 추가 StampView

### ISSUE THREAD

**Issue by hwseohyun** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#22]
# ✏️ Description
- 눈도장 찍는 StampView 개발

# 🛠️ Todo
- [ ] 실시간 날씨 데이터 가져와서 그에 따라 다른 멘트 제공
- [ ] 멘트 인터랙션 구현(선택사항) 
- [ ] 만들어둔 CalendarScene > StampLargeView 가져와서 도장 찍은 후 장면 구현
- [ ] 눈도장 찍기 버튼 누르면 흑백 -> 컬러로 바뀌고, 멘트 바뀌게
- [ ] 눈도장 찍기 버튼 누르면 눈동자 움직임 그대로 멈추고, 멈춘 장면 저장되게
