### ISSUE TITLE
[Feat] 구현 AttendanceView UI & 기능 구현

### ISSUE THREAD

**Issue by hwseohyun** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#24]
# ✏️ Description
- AttendanceView UI 개발

# 🛠️ Todo
- [ ] 실시간 날씨 데이터 가져와서 그에 따라 다른 멘트 제공
- [ ] 멘트 인터랙션 구현(선택사항) 
- [ ] 흰색 배경의 eye tracking view 그리기
- [ ] 눈도장 찍기 버튼 누르면 흑백 -> 컬러 (AttendanceCompletedView로 넘어가기) 구현
- [ ] 눈도장 찍기 버튼 누르면 눈동자 움직임 그대로 멈추고, 멈춘 장면 저장되게
