### ISSUE TITLE
[Feat] 구현 App flow 완성하기

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#27]
# ✏️ Description
- app flow 완성하기

# 🛠️ Todo
- [ ] app flow 완성하기 + 데이터 흐름
- [x] app delegate 완성하기
    - [x] log in 유지되도록 하기 (계속)
    - [x] app이 active 상태가 되면, userState에 따라 시작하는 View가 다르게
    - [x] OnBoardingView를 최초 1회만 경험하게
