### ISSUE TITLE
[Feat] 생성 AptView 안내방송 및 아파트 UI 구현, 수정

### ISSUE THREAD

**Issue by hwseohyun** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#56]
# ✏️ Description
- AptView 안내방송 및 아파트 UI 구현, 수정

# 🛠️ Todo
- [x] 안내방송 멘트 UI 구현
- [x] 아파트 창틀 디자인 추가
- [ ] 방 벽지 이미지 변경
