### ISSUE TITLE
[Feat] 수정 안내방송 멘트 UI 및 폰트 수정

### ISSUE THREAD

**Issue by hwseohyun** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#71]
# ✏️ Description
- 수정 안내방송 멘트 UI 및 폰트 수정

# 🛠️ Todo
- [ ] 안내방송 멘트 위치 수정
- [ ] 안내방송 custom font 적용
- [ ] 확성기 아이콘 추가 및 멘트 유무와 연동
