### ISSUE TITLE
[Feat] 수정: 출시 전까지 필요한 기능들

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#81]
# ✏️ Description
- 출시 전까지 필요한 기능들 정리

# 🛠️ Todo
- [ ] Feat: 기능 정상화: DispatchQueue 사용하는 부분 수정
- [ ] Feat: 푸시 알림 타이머
- [ ] UI: 푸시 보냈다는 흔적
- [ ] UI: .sleep, .inactive UI 수정
