### ISSUE TITLE
[FEAT] 수정 각종 버그 및 코드 수정사항

### ISSUE THREAD

**Issue by OreobrO** [DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa#91]
# ✏️ Description
**버그**
- 깨우기 누르는 버튼 앱 껐다 키면 초기화되면서 남은 시간이 보여지지 않는 점

**수정**
- 상대방의 색상을 반영하는 것
- 달력 데이터 다운로드하는 것
- 가로모드 제한

# 🛠️ Todo
- [ ] 깨우기 버튼 클릭 시 UserDefault에 저장하고, 앱을 껐다 켜도 다시 값을 불러와 status를 표시합니다.
- [ ] 상대방 roomUser의 색상을 AptView에 반영합니다.
- [ ] Portrait mode만 허용하도록 설정을 변경합니다.
- [ ] 달력에 표현될 AttendanceRecord를 다운로드하고 뷰에 반영합니다.
